### ISSUE TITLE
data reset on server restart

### ISSUE THREAD

**Issue by aglarcz** [EnvyWare/ReforgedBingo#1]
Hi, i am experiencing data reset on server restart sometimes for some players. Randomly without errors. 
I am using latest bingo on sponge 7.3 and sometimes players caught pokemon is reseted. Bingo card remains the same but they have to catch already caught pokemon as they are no longer green (completed) upon server restart.

**Comment by danorris709** [comment]
I can't replicate this. Is it happening when the server crashes?

**Comment by Steedr** [comment]
No, just simple restart (manual or mmcreboot). If you stay on the server during restart, it will reset all progress, but if disconnected right before restart it will be okay.

**Comment by danorris709** [comment]
Oh okay I see. Not sure if I can solve that to be honest. Kicking the players pre-reboot is usually a good strategy but I'll look into it I guess

**Comment by danorris709** [comment]
I believe this was fixed a while ago now, if not re-open please.
