### ISSUE TITLE
Spam to console log with config and crashes

### ISSUE THREAD

**Issue by SomeVagueRanks** [EnvyWare/ReforgedBingo#13]
![image](https://github.com/EnvyWare/ReforgedBingo/assets/124223603/b828c326-04f8-47e3-ab03-ae85f3f71903)

Crashes with the error :https://paste.helpch.at/hihiceneli.rb

The config was then updated to use our database but did not work.

**Comment by SomeVagueRanks** [comment]
![image](https://github.com/EnvyWare/ReforgedBingo/assets/124223603/bebe8a67-55f6-42a5-a872-0f797335d4da)
The only thing that was changed in the config

**Comment by danorris709** [comment]
You're using a version of Java that is not supported
