### ISSUE TITLE
data reset on server restart

### ISSUE THREAD

**Issue by aglarcz** [EnvyWare/ReforgedBingo#7]
Reopening #1 as it still happens when using latest ReforgedBingo-Forge-2.0.3-1.12.2:
"Hi, i am experiencing data reset on server restart sometimes for some players. Randomly without errors.
I am using latest bingo on sponge 7.4 and sometimes players caught pokemon is reseted. Bingo card remains the same but they have to catch already caught pokemon as they are no longer green (completed) upon server restart."

**Comment by aglarcz** [comment]
Update: its happening only to player who are online when server resets - if you log out before the restart then your bingo progress is saved and working as intended.

**Comment by danorris709** [comment]
Fixed in upcoming version
